home/urls.py
from django.conf.urls import url
from .views import index
from .views import returnRegister
from .views import register
from .custom_auth import auth_login, auth_logout

#url for app, add your URL Configuration

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^custom_auth/login/$', auth_login, name='auth_login'),
    url(r'^register/$', returnRegister, name='returnRegister'),
    url(r'^custom_auth/register/$', register, name='register'),
]

praktikum/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import home.urls as home
import narasumber_profile.urls as profile
from django.views.generic.base import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^home/', include(home,namespace='home')),
    url(r'^profile/', include(profile,namespace='profile')),
    url(r'^$', RedirectView.as_view(url='home/', permanent = True), name= 'index'),
]

home/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from __future__ import unicode_literals

from django.db import models


class AuthGroup(models.Model):
    name = models.CharField(unique=True, max_length=80)

    class Meta:
        managed = False
        db_table = 'auth_group'


class AuthGroupPermissions(models.Model):
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)
    permission = models.ForeignKey('AuthPermission', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_group_permissions'
        unique_together = (('group', 'permission'),)


class AuthPermission(models.Model):
    name = models.CharField(max_length=255)
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING)
    codename = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'auth_permission'
        unique_together = (('content_type', 'codename'),)


class AuthUser(models.Model):
    password = models.CharField(max_length=128)
    last_login = models.DateTimeField(blank=True, null=True)
    is_superuser = models.BooleanField()
    username = models.CharField(unique=True, max_length=150)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    email = models.CharField(max_length=254)
    is_staff = models.BooleanField()
    is_active = models.BooleanField()
    date_joined = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'auth_user'


class AuthUserGroups(models.Model):
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_groups'
        unique_together = (('user', 'group'),)


class AuthUserUserPermissions(models.Model):
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    permission = models.ForeignKey(AuthPermission, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_user_permissions'
        unique_together = (('user', 'permission'),)


class DjangoAdminLog(models.Model):
    action_time = models.DateTimeField()
    object_id = models.TextField(blank=True, null=True)
    object_repr = models.CharField(max_length=200)
    action_flag = models.SmallIntegerField()
    change_message = models.TextField()
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING, blank=True, null=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'django_admin_log'


class DjangoContentType(models.Model):
    app_label = models.CharField(max_length=100)
    model = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'django_content_type'
        unique_together = (('app_label', 'model'),)


class DjangoMigrations(models.Model):
    app = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    applied = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_migrations'


class DjangoSession(models.Model):
    session_key = models.CharField(primary_key=True, max_length=40)
    session_data = models.TextField()
    expire_date = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_session'


class Dosen(models.Model):
    id_narasumber = models.ForeignKey('Narasumber', models.DO_NOTHING, db_column='id_narasumber', primary_key=True)
    nik_dosen = models.CharField(max_length=20)
    jurusan = models.CharField(max_length=20)

    class Meta:
        managed = False
        db_table = 'dosen'


class Mahasiswa(models.Model):
    id_narasumber = models.ForeignKey('Narasumber', models.DO_NOTHING, db_column='id_narasumber', primary_key=True)
    npm = models.CharField(max_length=20)
    status = models.CharField(max_length=20)

    class Meta:
        managed = False
        db_table = 'mahasiswa'


class Narasumber(models.Model):
    id = models.IntegerField(primary_key=True)
    nama = models.CharField(max_length=30)
    email = models.CharField(max_length=30)
    tempat = models.CharField(max_length=30)
    no_hp = models.CharField(max_length=30)
    jumlah_berita = models.IntegerField()
    rerata_kata = models.IntegerField()
    id_universitas = models.ForeignKey('Universitas', models.DO_NOTHING, db_column='id_universitas')
    username = models.CharField(max_length=30, blank=True, null=True)
    password = models.CharField(max_length=30, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'narasumber'


class Staf(models.Model):
    id_narasumber = models.ForeignKey(Narasumber, models.DO_NOTHING, db_column='id_narasumber', primary_key=True)
    nik_staf = models.CharField(max_length=20)
    posisi = models.CharField(max_length=20)

    class Meta:
        managed = False
        db_table = 'staf'


class Universitas(models.Model):
    id = models.IntegerField(primary_key=True)
    jalan = models.CharField(max_length=30)
    kelurahan = models.CharField(max_length=30)
    kecamatan = models.CharField(max_length=30)
    provinsi = models.CharField(max_length=30)
    kodepos = models.IntegerField()
    website = models.CharField(max_length=30)

    class Meta:
        managed = False
        db_table = 'universitas'

home/views.py
from django.shortcuts import render
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import Narasumber, Mahasiswa, Dosen, Staf, Universitas
from django.db import connection

# Create your views here.
response={}
def index(request):
  html = 'landingpage.html'
  response['status'] = {'status': 'true'}
  return render(request, html, response)

def returnRegister(request):
  response['status'] = {'status': 'true'}
  html = 'register.html'
  return render(request, html,response)


def register(request):
    if request.method == "POST":
        username = request.POST['name']
        password = request.POST['password']
       	email = request.POST['email']
       	niknpm = request.POST['niknpm']
       	nohp = request.POST['nohp']
       	tanggal = request.POST['tanggal']
       	tempat = request.POST['tempat']
       	radio_value = request.POST.get('radio')
        status = request.POST['status']
        idUniversitas = request.POST['idUniversitas']

        pid = 0;

        for p in Narasumber.objects.raw('SELECT * FROM narasumber;'):
          if int(p.id) > pid:
            pid = int(p.id)


        exist = False
        u = Narasumber.objects.raw('SELECT * FROM NARASUMBER WHERE username=%s;',[username])
        for x in u:
          print(x)
          exist = True
          
        if (exist):
          messages.error(request, "Username sudah terdaftar")
          request.session['status'] = 'true'
          print('AHHAHAHHAHAHHAHAH')
          response['status'] = {'status': 'false'}
        else:
          try:
            with connection.cursor() as cursor:
              cursor.execute("INSERT INTO NARASUMBER(id, nama, email, tempat, no_hp, jumlah_berita, rerata_kata, id_universitas, username, password) VALUES (%s, %s, %s,%s, %s, %s, %s, %s, %s, %s);", [pid+1, username, email, tempat, nohp, 0, 0, 11111, username, password])
              if radio_value == 'mahasiswa':
                cursor.execute("INSERT INTO MAHASISWA(id_narasumber, npm, status) VALUES (%s, %s, %s);", [pid+1, niknpm, status])
              elif radio_value == 'dosen':
                cursor.execute("INSERT INTO DOSEN(id_narasumber, nik_dosen, jurusan) VALUES (%s, %s, %s);", [pid+1, niknpm, 'Ilmu Komputer'])
              else:
                cursor.execute("INSERT INTO STAF(id_narasumber, nik_dosen, posisi) VALUES (%s, %s, %s);", [pid+1, niknpm, 'Staff'])
              request.session['status'] = 'true'
              response['status'] = {'status': 'true'}
          except Exception as e:
            print(e)
    html = 'register.html'
    return render(request, html, response)

home/templates/landingpage.html
<!DOCTYPE html>
<html>
<head>
<title>BMNC</title>
<link rel="icon" href="asset/bmnc.png" type="image/gif" sizes="32x32">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link href="https://fonts.googleapis.com/css?family=Comfortaa" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet">
<style>
	* {box-sizing: border-box;}
html{
	height: 100%;
	width: 100%;
}

body { 
	margin: 0;
	font-family: 'Comfortaa', cursive;
	/*font-family: 'Varela Round', sans-serif;*/
	background: linear-gradient(to bottom right, #33cccc -2%, #ffc1b8 105%);
	min-height: 100%;
	background-attachment: fixed;
}


.header {
  overflow: hidden;
  background-color: white; 
  padding: 10px 5px;
  -webkit-box-shadow: 0 3px 5px rgba(57, 63, 72, 0.3);
  -moz-box-shadow: 0 3px 5px rgba(57, 63, 72, 0.3);
  box-shadow: 0 3px 5px rgba(57, 63, 72, 0.3);
}

.logo{
	margin-left: 20px;
	height: 40px;
}
.img{
	width: 110px;
	height: 40px;
}

.header a {
  float: left;
  color: black;
  text-align: center;
  padding: 12px;
  text-decoration: none;
  font-size: 18px; 
  line-height: 25px;
  border-radius: 4px;
}

.header a.logo {
  font-size: 25px;
  font-weight: bold;
}

.header a:hover {
  background-color: #ddd;
  color: black;
}

.header a.active {
  background-color: dodgerblue;
  color: white;
}

.header-right {
  float: right;
}

@media screen and (max-width: 500px) {
  .header a {
    float: none;
    display: block;
    text-align: left;
  }
  .header-right {
    float: none;
  }
}

.body-right{
	width: 40%;
	float: right;
}
.body-left{
	width: 60%;
	float: left;
	margin-bottom: 40px;
}

.form{
	display: flex;
	flex-direction: column;
	flex-wrap: wrap;
	align-content: center;
}

:focus{outline: none;}

.content-title{
	margin: 40px auto;
	margin-top: 0px;
	width: 80%;
	border-bottom: 1px solid #3333;
}
.content-titles{
	margin: 10px auto;
	margin-top: 0px;
	width: 80%;
	border-bottom: 1px solid #3333;

}

.content-title, .content-titles h1{
	font-weight: bold;
	color: #06516B;

}

.col-3{
	width: 40%; 
	margin: 10px 30%; 
	justify-content: center;
	position: relative;
	} /* necessary to give position: relative to parent. */

input[type="text"]{
	font-family: 'Comfortaa', cursive; 
	margin:auto;
	color: #333; 
	width: 150px; 
	box-sizing: border-box; 
	letter-spacing: 1px;
}

input[type="submit"]{
	font-family: 'Comfortaa', cursive; 
}

input::-webkit-input-placeholder {
    font-size: 15px;
    line-height: 3;
    letter-spacing: 1px;
}


.effect-2{
	border: 0; 
	padding: 7px 0; 
	border-bottom: 1px solid #ccc;
	margin:auto;
	width: 150px;
}

.effect-2 ~ .focus-border{
	position: absolute; 
	bottom: 0; 
	left: 50%; 
	width: 0; 
	height: 2px; 
	background-color: #3399FF; 
	transition: 0.4s;
}
.effect-2:focus ~ .focus-border{
	width: 150px; 
	transition: 0.4s; 
	left: 0;
}

::-webkit-input-placeholder {
   text-align: center;

}

:-moz-placeholder {
   text-align: center;

}

.buttons{
	align-items: center;
	align-content: center;
	align-self: center;
	margin-top: 60px;
}

.buttons p{
	margin-top: 30px;
	text-align: center;
}

.button {
  background: #FFC1B8;
  border-radius: 100px;
  width: 150px;
  height: 40px;
  padding: 10px 20px;
  color: #06516B;
  text-decoration: none;
  font-size: 18px;
  

  margin-bottom: -10px;
  margin-left: 120px;
  text-align: center;
  -webkit-box-shadow: 0 3px 5px rgba(57, 63, 72, 0.3);
  -moz-box-shadow: 0 3px 5px rgba(57, 63, 72, 0.3);
  box-shadow: 0 3px 5px rgba(57, 63, 72, 0.3);
}


.button:hover{
	cursor: pointer;
	opacity: 0.75;
}

.p{
	border-bottom: 1px solid black;
	width: 25%;
	margin:auto;
}
.p:hover{
	cursor: pointer;
	color: grey;
}

.container {
    width: 400px;
    height: 500px;
    background: white;
    float: right;
    margin-top: 130px;
    margin-right: 50px;
    bottom: 0;
    right: 100px;
    border-radius: 40px;
    border-bottom: 1px solid rgba(255, 255, 255, 0.3);
    box-shadow: 2px 2px 20px rgba(0, 0, 0, 0.3);
  }

.content-container {
	width: 95%;
	height: 100%;
	position: relative;
	margin: auto;
	display: flex;
	flex-direction: column;
	justify-content: center;
}

.content-def{
	width: 80%;
	align-self: center;
	text-align: justify;
	color: #666;
}

.containers {
    width: 760px;
    height: 400px;
    background: white;
    float: right;
    margin-top: 50px;
    margin-right: 50px;
    bottom: 0;
    right: 100px;
    border-radius: 40px;
    border-bottom: 1px solid rgba(255, 255, 255, 0.3);
    box-shadow: 2px 2px 20px rgba(0, 0, 0, 0.3);
}
.containers1 {
    width: 760px;
    height: 300px;
    background: white;
    float: right;
    margin-top: 50px;
    margin-right: 50px;
    bottom: 0;
    right: 100px;
    border-radius: 40px;
    border-bottom: 1px solid rgba(255, 255, 255, 0.3);
    box-shadow: 2px 2px 20px rgba(0, 0, 0, 0.3);
  }

label {
	color: #E74C3C;
	text-transform: uppercase;
}

</style>
</head>
<body>
<div class="header">
	<div href="#default" class="logo">
		{% load static %}
		<img src="{% static "image/logo.png" %}" class="img">
	</div>
  	<div class="header-right">
    </div>
</div>

<div class="body">
	<div class="body-right">
		<div class="container">
	  		<div class="content-container">
	  			<div class="content-title">
	  				<h1>User Login</h1>
	  			</div>
	  			<form action="{% url 'home:auth_login' %}" method="POST">
	  				{% csrf_token %}
		    		<div class="form">
		    			<div class="col-3">
	        				<input for = "username" class="effect-2" type="text" name="username" placeholder="Username" required>
	            				<span class="focus-border"></span>
	        			</div>
	        			<div class="col-3">
	        				<input for = "password" class="effect-2" type="Password" name="password" placeholder="Password" required>
	            				<span class="focus-border"></span>
	        			</div>
		    		</div>
		    		<div class="buttons">
		    			<input type="submit" class="button" value="Login"></input>
		    			<p> or </p>
		    			<p class="p"> Register</p>
		    		</div>
		    	</form>
  			</div>
		</div>
	</div>
	<div class="body-left">
		<div class="containers">
	  		<div class="content-container">
	  			<div class="content-titles">
	  				<h1> What is BMNC?</h1>
	  			</div>
	  			<div class="content-def">
	  				<p><b>BMNC is a project of Database Implementation by Athifah, Kirana, and Zulia</b></p>
	  				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
	  				Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. 
	  				</p>
	  			</div>
	  		
  			</div>
		</div>
		<div class="containers1">
	  		<div class="content-container">
	  			<div class="content-titles">
	  				<h1> Why use BMNC?</h1>
	  			</div>
	  			<div class="content-def">
	  				<p><b>BMNC is a project of Database Implementation by Athifah, Kirana, and Zulia</b></p>
	  				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
	  				</p>
	  			</div>
	  		
  			</div>
		</div>
	</div>
</div>
</body>
</html>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"> </script>
<script>
	$(document).ready(function(){
		var status = ({{status.status}});
		if (!status){
			alert('Username dan password salah!');
		}
	}); 
	$('.p').click(function(){
		window.location.href = 'register';
		console.log('sampai ga');
	});

</script>

home/templates/register.html
<!DOCTYPE html>
<html>
<head>
<title>BMNC</title>
<link rel="icon" href="asset/bmnc.png" type="image/gif" sizes="32x32">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link href="https://fonts.googleapis.com/css?family=Comfortaa" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet">
<style>
	* {box-sizing: border-box;}
html{
	overflow-x: hidden;
	height: 100%;
	width: 100%;
}
body { 
  margin: 0;
  font-family: 'Comfortaa', cursive;
  /*font-family: 'Varela Round', sans-serif;*/
  background: linear-gradient(to bottom right, #33cccc -2%, #ffc1b8 105%);
  background-attachment: fixed;
  min-height: 100%;
}

.header {
  overflow: hidden;
  background-color: white; 
  padding: 10px 5px;
  -webkit-box-shadow: 0 3px 5px rgba(57, 63, 72, 0.3);
  -moz-box-shadow: 0 3px 5px rgba(57, 63, 72, 0.3);
  box-shadow: 0 3px 5px rgba(57, 63, 72, 0.3);
}
.home{
	vertical-align: middle;
	margin-top: -15px;
}
.home:hover{
	color:#06516B;
	cursor: pointer;
}

.logo{
	margin-left: 20px;
	height: 40px;
}
.img{
	width: 110px;
	height: 40px;

}

.personimg{
	width: 44px;
	height: 44px;
	margin-top:-30px;
	margin-left: 20px;
	margin-right: 20px;
}

.header a {
  float: left;
  color: black;
  text-align: center;
  padding: 12px;
  text-decoration: none;
  font-size: 18px; 
  line-height: 25px;
  border-radius: 4px;
}

.header a.logo {
  font-size: 25px;
  font-weight: bold;
}

.header a:hover {
  background-color: #ddd;
  color: black;
}

.header a.active {
  background-color: dodgerblue;
  color: white;
}

.header-right {
  float: right;
  vertical-align: middle;
  margin-top:-10px;
  vertical-align: middle;
  display: flex;
  flex-direction: row;
}

.container-header p{
	margin-top: 1px;
	color: #06516B;
}

.container-header p:hover{
	color: #058896;
	cursor: pointer;

}

.personimg:hover + .container-header{
	display: block;
}

@media screen and (max-width: 500px) {
  .header a {
    float: none;
    display: block;
    text-align: left;
  }
  .header-right {
    float: none;
  }
}

.containers{
	width: 600px;
    height: 650px;
    margin: 50px auto;
}
.container-header {
	display: none;
    width: 250px;
    height: 50px;
    background: white;
    float: right;
    margin-top: -30px;
    margin-right: 20px;
    bottom: 0;
    right: 100px;
    border-radius: 25px;
    border-bottom: 1px solid rgba(255, 255, 255, 0.3);
    border: 49px solid transparent;
    box-shadow: 2px 2px 20px rgba(0, 0, 0, 0.3);
}

.container-body {
    width: 600px;
    height: 650px;
    background: white;
    float: left;
    border-radius: 40px;
    border-bottom: 1px solid rgba(255, 255, 255, 0.3);
    border: 49px solid transparent;
    box-shadow: 2px 2px 20px rgba(0, 0, 0, 0.3);
}



.body{
	width: 100%;
	height: 100%;
}
.title{
	border-bottom: 1px solid #E6E6E6;
}
.title h1{
	text-align: center;
	color: #06516B;
}
.acc-form{
	display: flex;
	flex-direction: row;
}

.input{
	width: 200px;
	height: 30px;
	border-radius: 50px;
	
}
.label{
	display: flex;
	flex-direction: column;
	width: 50%;
	margin-left: 30px;
}
.label label{
	margin-top: 20.9px;
	color: #06516B;
}
.input{
	display: flex;
	flex-direction: column;
	width: 50%;
}
.input input{
	margin-top: 10px;
	border: 1px solid #E6E6E6;;
	font-size: 10px;
	width: 100%;
	padding: 8px 15px;
	border-radius: 60px;
	color: #06516B;
	letter-spacing: 0.01em;
	position: relative;
}
.div { 
	position: relative;
	width: 40%;
}
.title-acc{
	margin-bottom: -20px;
}
.title-acc h2{
	color: #06516B;

}

input[type="checkbox"], input[type="radio"] {
    position: absolute;
    z-index: 999; /*so you can click on the :after */
    top: 0; left: 0;
    width: 100%;
    height: 100%;
    min-height: 2em; 
    opacity: 0;
    -webkit-appearance: none;
    -moz-appearance: none;
    -ms-appearance: none;
    appearance: none;
}

section {
   margin-top: -2px;
   height: 0;
   overflow: hidden;
   max-height: 0;
   -webkit-transition: 1s all;
}

label:after {
    content: '';
    position: absolute;
    right: .5em;
    top: 0;
}

input[type="checkbox"]:active + label,
input[type="radio"]:active + label{
  background: #ccc; 
}

input[type="checkbox"]:checked ~ section {
    height: auto;
    max-height: 12em;
}



.selection {
    position: relative;
    padding: 0;
    margin: 0;
    width: 100%
}

input[type="radio"]:checked + label {
    background: #333;
    color: white;
}

input[type="radio"]:checked + label:after {
    position: absolute;
    right: .5em;
    top: .25em;
    content: '✓';
    color: black;
}
*:focus {
    outline: none;
}
.status{
	display: flex;
	flex-direction: row;
	margin-top:5px;
}
.status label{
	margin-top: 10px;
}
.status input{
	float:right;
	margin-top: 5px;
	margin-left: 20px;
	width: 85px;
}

.role{
	color: #06516B;
	width: 60%;
	float:left;
}


.buttons p{
	text-align: center;
}

.button {
	background: #FFC1B8;
	border-radius: 100px;
	width: 150px;
	height: 40px;
	padding: 10px 20px;
	color: #06516B;
	text-decoration: none;
	font-size: 18px;
	margin-top: 100px;
	text-align: center;
	-webkit-box-shadow: 0 3px 5px rgba(57, 63, 72, 0.3);
	-moz-box-shadow: 0 3px 5px rgba(57, 63, 72, 0.3);
	box-shadow: 0 3px 5px rgba(57, 63, 72, 0.3);
	border-color: transparent;
}

.button:hover{
	cursor: pointer;
	opacity: 0.75;
}

.link{
	margin-top: -25px;
	margin-left:40px;
}

.status-s{
	display: flex;
	flex-direction: row;
	margin-top:5px;
}
.status-s label{
	margin-top: 10px;
}
.status-s input{
	float:right;
	margin-top: 5px;
	margin-left: 20px;
	width: 100px;
}

</style>
</head>
<body>
	<div class="header">
		<div href="#default" class="logo">
		{% load static %}
		<img src="{% static "image/logo.png" %}" class="img">
		</div>
	</div>
	<div class="body">
		<div class=containers>
			<form action="{% url 'home:register' %}" method="POST">
				{% csrf_token %}
				<div class="container-body">
					<div class="title">
						<h1>Regristration Form</h1>
					</div>
					<div class="account">
						<div class="title-acc">
							<h2>Account</h2>
						</div>
						<div class="acc-form">
							<div class="label">
								<label>Name</label>
								<label>Password</label>
								<label>Email</label>
								<label>NPM</label>
								<label>Phone Number</label>
								<label>Date of Birth</label>
								<label>Place of Birth</label>
							</div>
							<div class="input">
								<input type="text" placeholder="e.g., 'Zulia Putri', 'Ini Budi'" for="name" name="name" required>
								<input type="Password" placeholder="e.g., panjang minimal 8 karakter" for="password" name="password" required>
								<input type="text" placeholder="e.g., zulia.putri@dummy.ac.id" for="email" name="email" required>
								<input type="text" placeholder="e.g., 1234567890" for="niknpm" name="niknpm" required>
								<input type="text" placeholder="e.g., 0812345678, 081231838" for="nohp" name="nohp" required>
								<input type="text" placeholder="e.g., 1990-2-31" for="tanggal" name="tanggal" required>
								<input type="text" placeholder="e.g., 'Padang', 'Maluku'" for="tempat" name="tempat" required>
							</div>
						</div>
					</div>
					<div class="role">
						<h2>Role</h2>
							<div class="div">
								<input type="checkbox"/>
								<label class="headlabel" id="headlabel">Select Role ▾</label>

								<section>
									<div class="selection">
										<input id="mahasiswa" for="mahasiswa" value="mahasiswa" name="radio" type="radio" name="hellomoto"/>
										<label class="mahasiswa">Mahasiswa</label>
									</div>
									<div class="selection">
										<input id="dosen" for="dosen" name="radio" value="dosen" type="radio" name="hellomoto"/>
										<label class="dosen" >Dosen</label>
									</div>
									<div class="selection">
										<input id="staff" for="staff" name="radio" value="staff" type="radio" name="hellomoto"/>
										<label class="staff" >Staff</label>
									</div>
								</section>
							</div>
							<div class="status" id="status">
								<label> Status</label>
								<div class="input">
									<input type="text" for="status" name="status" placeholder="Aktif/Pasif">
								</div>
							</div>
							<div class="status-s" id="status-s">
								<label> ID universitas</label>
								<div class="input">
									<input type="text" for="idUniversitas" name="idUniversitas" placeholder="e.g., 1039293">
								</div>
							</div>
						</div>
			    		<input type="submit" class="button"></input>
					</div>
				</form>
			</div>
		</div>
</body>
</html>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"> </script>
<script>
	$(document).ready(function(){
		var status = ({{status.status}});
		if (!status){
			alert('Username sudah ada!');
		}
		$(".status").hide();
		$(".status-s").hide();
		//console.log(status)
	});
	$("#personimg").click(function(){
		var personimg = document.getElementById("personimg");
		personimg.src = 'asset/person-selected.png';
		personimg.style.cursor = 'pointer';
		if ($('.container-header').is(':visible')){
			$('.container-header').hide();
			personimg.src = 'asset/person-undetected.png';
		}else{
			$('.container-header').show();
		}

	});
	$("#mahasiswa").click(function(){
		document.getElementById("headlabel").innerHTML = "Mahasiswa ▾";
		$(".status").show();
		$(".status-s").hide();
	});
	$("#dosen").click(function(){
		document.getElementById("headlabel").innerHTML = "Dosen ▾";
		$(".status").hide();
		$(".status-s").show();
	});
	$("#staff").click(function(){
		document.getElementById("headlabel").innerHTML = "Staff ▾";
		$(".status").hide();
		$(".status-s").show();
	});

</script>